app: sykepengesoknad-korrigering-metrikk
namespace: flex
team: flex
kafkaPool: nav-dev
cpu: 100m
memory: 300Mi
azureTenant: trygdeetaten.no
env:
  SYKEPENGESOKNAD_BACKEND_AAD_CLIENT_ID: dev-gcp.flex.sykepengesoknad-backend
