app: sykepengesoknad-korrigering-metrikk
namespace: flex
team: flex
kafkaPool: nav-prod
cpu: 200m
memory: 400Mi
azureTenant: nav.no
env:
  SYKEPENGESOKNAD_BACKEND_AAD_CLIENT_ID: prod-gcp.flex.sykepengesoknad-backend
